# Generated by Django 5.1.1 on 2025-03-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0002_course_courses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="courses",
            new_name="trainees",
        ),
    ]
