# Generated by Django 5.1.1 on 2025-03-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee", "0003_rename_courses_course_trainees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="trainees",
        ),
        migrations.AddField(
            model_name="course",
            name="trainee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="trainee.trainee",
            ),
        ),
    ]
